// BJJ Position Reference — comprehensive map of all game positions.
// Each entry covers: description, available attacks, transitions, counters, and tips.
// This is the ground truth for the Library tab's "Position Guide" view.

const bjjPositionGuide = [
  {
    id: "Standing",
    name: "Standing",
    icon: "🤼",
    tier: "Neutral",
    description: "Both fighters on their feet. The match starts here and resets here after scrambles. Everything begins with hand fighting.",
    gameCards: ["Collar Tie", "Wrist Control", "Snapdown", "Double Leg", "Single Leg", "Guard Pull", "Arm Drag", "Duck Under", "Sprawl", "Ankle Pick"],
    attacks: ["Double Leg → Top Half Guard", "Single Leg → Top Half Guard", "Arm Drag → Back Control", "Duck Under → Back Control"],
    submissions: ["Standing Guillotine (on a shot)", "Anaconda (on a front headlock)"],
    transitionsTo: ["Top Half Guard (takedowns)", "Bottom Guard (guard pull)", "Front Headlock (sprawl)"],
    chainSetups: ["Collar Tie → Snapdown", "Wrist Control → Arm Drag"],
    missingInGame: ["Ankle Pick (in skills only)", "Hip Toss", "Foot Sweeps (O-uchi, D'ashi harai)", "Fireman's Carry"],
    tip: "Sweeps and takedowns score 2 pts. Control is earned through setups. The player who wins the collar tie or wrist fight usually dictates the takedown."
  },
  {
    id: "Front Headlock",
    name: "Front Headlock",
    icon: "🔒",
    tier: "Neutral / Dominant",
    description: "Your arm is under their chin, controlling their head. One of the most dangerous positions for chokes. Opponent is caught leaning forward with no posting hand.",
    gameCards: ["Headlock Pressure", "Slide By", "Guillotine", "D'Arce", "Anaconda", "Front Headlock Spin"],
    attacks: ["Guillotine", "D'Arce", "Anaconda", "Go-behind to Back Control"],
    submissions: ["Guillotine (35% base)", "D'Arce", "Anaconda"],
    transitionsTo: ["Back Control (slide by, spin behind)", "Standing (they escape)"],
    chainSetups: ["Snapdown → Headlock Pressure → Guillotine"],
    missingInGame: ["Twister entry (exotic)", "North-South transition"],
    tip: "Headlock Pressure adds control AND drains their stamina before you attempt the choke. Stack control first, then attack — submissions from here are devastating with chains."
  },
  {
    id: "Bottom Guard",
    name: "Bottom Guard",
    icon: "🛡️",
    tier: "Bottom",
    description: "You are on your back, opponent between your legs. This is your offensive bottom position. You can attack submissions and sweep in all directions.",
    gameCards: ["Armbar", "Triangle", "Kimura", "Omoplata", "Guillotine", "Hip Bump Sweep", "Scissor Sweep", "Flower Sweep", "Butterfly Hooks", "Butterfly Sweep", "Ashi Garami Entry", "Guard Pull", "Wrist Control"],
    attacks: ["Triangle", "Armbar", "Kimura", "Omoplata", "Hip Bump → Mount", "Scissor → Top Guard", "Butterfly → Top Half Guard"],
    submissions: ["Armbar (35% base)", "Triangle (35% base)", "Kimura", "Guillotine"],
    transitionsTo: ["Mount (hip bump sweep)", "Top Guard (scissor sweep)", "Top Half Guard (butterfly sweep)", "Ashi Garami (entry)"],
    chainSetups: ["Guard Pull → Triangle", "Butterfly Hooks → Butterfly Sweep", "Butterfly Hooks → Ashi Garami Entry", "Hip Bump Sweep → Armbar"],
    missingInGame: ["De La Riva Guard", "Spider Guard", "Lasso Guard", "X-Guard", "50/50", "Berimbolo"],
    tip: "IMPORTANT: Control from here boosts your submission %, but sweeps always land regardless of control. Stack control for Triangle/Armbar attacks, not for sweeps. The Butterfly Hooks → Butterfly Sweep chain is your most direct path."
  },
  {
    id: "Top Guard",
    name: "Top Guard",
    icon: "⚖️",
    tier: "Passing",
    description: "Opponent is on their back between your legs — or you are standing over them in open guard. Your job is to pass their legs and reach side control.",
    gameCards: ["Knee Slice", "Torreando", "X-Pass", "Body Lock Pass", "Leg Drag", "Backstep Pass", "Pressure", "Wrist Control"],
    attacks: ["Knee Slice → Side Control", "Torreando → Side Control", "Body Lock → Side Control"],
    submissions: ["None directly — pass first"],
    transitionsTo: ["Side Control (passes)", "Bottom Guard (if swept)"],
    chainSetups: ["Scissor Sweep → Knee Slice (after reversal)"],
    missingInGame: ["Double Under Pass", "Stack Pass", "Combat Base"],
    tip: "You score 3 pts for passing to Side Control. Pressure card builds control here, which is useful when you later attempt submissions from mount."
  },
  {
    id: "Bottom Half Guard",
    name: "Bottom Half Guard",
    icon: "🔄",
    tier: "Bottom",
    description: "You have one of their legs trapped between yours. You are partially under them. Your goal is to either sweep, recover full guard, or enter a leg lock.",
    gameCards: ["Butterfly Hooks", "Butterfly Sweep", "Old School Sweep", "Ashi Garami Entry", "Hip Escape", "Frame", "Reguard", "Technical Standup"],
    attacks: ["Old School → Top Half Guard", "Butterfly → Top Half Guard", "Ashi Garami Entry"],
    submissions: ["None directly — sweep or enter legs first"],
    transitionsTo: ["Top Half Guard (old school/butterfly sweep)", "Bottom Guard (reguard)", "Ashi Garami (entry)", "Standing (technical standup)"],
    chainSetups: ["Butterfly Hooks → Butterfly Sweep", "Butterfly Hooks → Ashi Garami Entry"],
    missingInGame: ["Deep Half Guard", "Z-Guard / Knee Shield", "Lockdown", "Dogfight Position", "Waiter Sweep"],
    tip: "Setting Butterfly Hooks first is the correct chain — it adds control AND then your sweep or leg entry gets a bonus. Old School Sweep leads to Top Half Guard where you can Knee Slice for an additional chain."
  },
  {
    id: "Top Half Guard",
    name: "Top Half Guard",
    icon: "⬆️",
    tier: "Passing",
    description: "You have half their legs free — you are on top but they still have one of your legs trapped. Pass to gain full control.",
    gameCards: ["Knee Slice", "Backstep Pass", "Leg Drag", "Shin Pin Pass", "Pressure", "Body Lock Pass"],
    attacks: ["Knee Slice → Side Control", "Body Lock Pass → Side Control"],
    submissions: ["None directly — pass first"],
    transitionsTo: ["Side Control (passes)", "Bottom Half Guard (if swept)"],
    chainSetups: ["Old School Sweep → Knee Slice (chain bonus after sweep reversal)", "Butterfly Sweep → Knee Slice (chain bonus after sweep reversal)"],
    missingInGame: ["Headquarters Position", "Electric Chair Submission"],
    tip: "After sweeping to Top Half Guard, immediately chain into Knee Slice for a control bonus. This is the intended combo path."
  },
  {
    id: "Side Control",
    name: "Side Control",
    icon: "🏋️",
    tier: "Dominant",
    description: "You are beside them, chest to chest, no legs in the way. 3 points for getting here. Advance to mount or hunt for shoulder locks.",
    gameCards: ["Mount", "Knee On Belly", "North-South Control", "Americana", "Kimura", "Arm Triangle", "Pressure"],
    attacks: ["Step to Mount → Mount (+4 pts)", "Knee on Belly → standing threat", "Americana", "Kimura", "Arm Triangle"],
    submissions: ["Americana", "Kimura", "Arm Triangle"],
    transitionsTo: ["Mount (step over)", "North-South (rotate)", "Bottom Half Guard (if escaped)"],
    chainSetups: ["Knee Slice → Mount (chain after passing)"],
    missingInGame: ["North-South Choke (key missing submission)", "Reverse Kesa Gatame", "Kimura trap series"],
    tip: "Pressure from Side Control builds control and drains them before the Americana or Kimura. The Arm Triangle is the highest-value submission from here."
  },
  {
    id: "Under Side Control",
    name: "Under Side Control",
    icon: "⬇️",
    tier: "Defensive",
    description: "You are on the bottom with their weight across your chest. Your priority is framing, creating space, and recovering guard.",
    gameCards: ["Frame", "Hip Escape", "Bridge", "Reguard", "Technical Bridge", "Technical Standup"],
    attacks: [],
    submissions: [],
    transitionsTo: ["Bottom Half Guard (hip escape)", "Bottom Guard (reguard)", "Turtle (technical bridge)", "Standing (technical standup)"],
    chainSetups: [],
    missingInGame: ["Sit-up to Single Leg (common real escape)"],
    tip: "Use Frame to reduce their control while you escape. Reguard + Frame is the cleanest path back to guard. Technical Standup sacrifices 2 pts but fully resets the match if you're exhausted."
  },
  {
    id: "Mount",
    name: "Mount",
    icon: "👑",
    tier: "Dominant",
    description: "You are sitting on their chest, both knees on the mat. 4 points. The most dominant position for submissions.",
    gameCards: ["Armbar", "Americana", "Arm Triangle", "Pressure"],
    attacks: ["Armbar", "Americana", "Arm Triangle", "Step to Back (advanced)"],
    submissions: ["Armbar (35% base +)", "Americana", "Arm Triangle"],
    transitionsTo: ["Back Control (if they roll)", "Side Control (if they escape partially)"],
    chainSetups: ["Mount → Arm Triangle (chain bonus)"],
    missingInGame: ["Ezekiel Choke (unique mount submission)", "S-Mount", "High Mount distinction"],
    tip: "Pressure first to drain their stamina, then attack the Armbar or Arm Triangle. The chain Mount → Arm Triangle gives +20% finish bonus. Control from here stacks multiplicatively with stamina drain."
  },
  {
    id: "Mounted",
    name: "Mounted",
    icon: "🙏",
    tier: "Defensive",
    description: "You are on the bottom with them on your chest. The most dangerous defensive position. Priority: escape fast before they attack.",
    gameCards: ["Bridge", "Hip Escape", "Elbow Escape", "Knee-Elbow Escape", "Frame"],
    attacks: [],
    submissions: [],
    transitionsTo: ["Bottom Half Guard (bridge)", "Bottom Half Guard (hip escape)", "Standing (if fully escaped)"],
    chainSetups: [],
    missingInGame: [],
    tip: "Bridge immediately while you still have stamina. Every turn you stay mounted they can attack a submission. Elbow Escape (also called Elbow-Knee) is slower but safer. Use Frame to reduce their control before bridging."
  },
  {
    id: "Back Control",
    name: "Back Control",
    icon: "🎯",
    tier: "Dominant",
    description: "You are on their back, hooks in, seatbelt grip. 4 points. The highest percentage position for finishes in all of BJJ.",
    gameCards: ["Rear Naked Choke", "Bow And Arrow", "Clock Choke", "Seatbelt Pressure", "Body Triangle"],
    attacks: ["RNC", "Bow and Arrow", "Clock Choke", "Body Triangle (control)"],
    submissions: ["Rear Naked Choke (35% base, highest %)", "Bow and Arrow", "Clock Choke"],
    transitionsTo: ["Side Control (if they escape hooks)", "Turtle (they defend and turn)"],
    chainSetups: ["Arm Drag → RNC", "Duck Under → RNC"],
    missingInGame: [],
    tip: "The RNC has the highest percentage of any submission in the game — Back Hunter style pushes it to ~57%+. Seatbelt Pressure adds control and stamina drain before the choke. This is the most powerful finishing position."
  },
  {
    id: "Back Taken",
    name: "Back Taken",
    icon: "😰",
    tier: "Defensive",
    description: "They are on your back with hooks and seatbelt. You need to peel hands and escape before the choke lands.",
    gameCards: ["Hand Fight", "Protect Neck", "Frame", "Technical Standup"],
    attacks: [],
    submissions: [],
    transitionsTo: ["Standing (hand fight escape)", "Under Side Control (partial escape)"],
    chainSetups: [],
    missingInGame: ["Seat belt defense roll (reversal)"],
    tip: "Protect Neck is your counter against submission attempts — it reduces their finish chance even if they attack. Hand Fight returns you to Standing and fully resets. Technical Standup costs 2 pts but is a guaranteed reset when stamina is low."
  },
  {
    id: "Turtle",
    name: "Turtle",
    icon: "🐢",
    tier: "Neutral / Defensive",
    description: "On all-fours, defending. A compromise position — neither fully escaped nor submitted. Opponent is circling for the back.",
    gameCards: ["Hand Fight", "Protect Neck", "Frame", "Technical Standup"],
    attacks: [],
    submissions: ["None from bottom turtle"],
    transitionsTo: ["Standing (hand fight)", "Back Taken (if they get hooks)", "Bottom Guard (reguard)"],
    chainSetups: [],
    missingInGame: ["Granby Roll (turtle escape to guard)", "Sit-out (counter from turtle)", "Crucifix (from top turtle)"],
    tip: "Turtle is a holding pattern, not a goal. Use Hand Fight to escape to standing as soon as possible. Staying in turtle gives the opponent time to take the back."
  },
  {
    id: "Ashi Garami",
    name: "Ashi Garami",
    icon: "🦵",
    tier: "Leg Lock Attack",
    description: "You have their leg trapped in a figure-four entanglement. Outside Ashi. This is your launching pad for all major leg lock finishes.",
    gameCards: ["Straight Ankle Lock", "Heel Hook", "Kneebar", "Toe Hold", "Ashi Control"],
    attacks: ["Straight Ankle Lock", "Heel Hook", "Kneebar", "Toe Hold"],
    submissions: ["Straight Ankle Lock (35% base)", "Heel Hook (35% base, high power)", "Kneebar", "Toe Hold"],
    transitionsTo: ["Bottom Guard (if they escape)", "50/50 (if they counter-entangle)"],
    chainSetups: ["Butterfly Hooks → Ashi Garami Entry", "Ashi Garami → Ankle Lock", "Ashi Garami → Heel Hook"],
    missingInGame: ["50/50 Position", "Outside Ashi vs Inside Ashi distinction", "Cross Ashi", "Single Leg X sub-position"],
    tip: "Ashi Control adds control (+1) before attempting the finish — use it for the bonus. Heel Hook has high power but the same base chance as Ankle Lock. Chains from Butterfly Hooks give +12% submission bonus. This position is the Leg Locker style's home."
  },
  {
    id: "Caught Ashi Garami",
    name: "Caught in Ashi",
    icon: "🚨",
    tier: "Defensive",
    description: "Your leg is trapped in their leg entanglement. Dangerous — leg locks attack the knee and ankle which have low pain tolerance and can damage quickly.",
    gameCards: ["Leg Pummel Escape", "Hip Escape", "Hand Fight", "Frame"],
    attacks: [],
    submissions: [],
    transitionsTo: ["Bottom Guard (escape)", "Standing (hand fight)"],
    chainSetups: [],
    missingInGame: ["Heel hook defense rotation", "Inverting to counter-entangle"],
    tip: "React immediately — every turn in Ashi Garami is a submission attempt waiting. Leg Pummel Escape is your specialized escape. Hip Escape also works. Do NOT just Frame and wait — that only reduces their control, not the submission threat."
  }
];

// Quick lookup map
const positionGuideById = Object.fromEntries(bjjPositionGuide.map((p) => [p.id, p]));
