// Expandable BJJ technique database.
// This is intentionally not the playable deck. Cards, skills, animations, and
// future collection screens can pull from this data without flooding matches.

const techniqueDatabase = [
  {
    id: "standing-neutral",
    name: "Standing Neutral",
    category: "Standing",
    subcategory: "Position",
    worksFrom: ["Match Start", "Standing"],
    leadsTo: ["Hand Fighting", "Collar Tie", "Wrist Control", "Level Change"],
    counters: ["Collar Tie", "Arm Drag", "Snapdown"],
    followUps: ["Wrist Control", "Collar Tie", "Level Change"],
    archetypeSynergies: ["Wrestler", "Back Hunter"],
    raritySuggestion: "Common",
    staminaSuggestion: 0,
    riskLevel: 1,
    rewardLevel: 1,
    unlockTier: "Base",
    notes: "Neutral starting point. Best used as the root of standing exchanges."
  },
  {
    id: "wrist-control",
    name: "Wrist Control",
    category: "Standing",
    subcategory: "Hand Fighting",
    worksFrom: ["Standing", "Bottom Guard", "Top Guard"],
    leadsTo: ["Arm Drag", "Russian Tie", "Snapdown", "Single Leg"],
    counters: ["Grip Break", "Pummel", "Posture"],
    followUps: ["Arm Drag", "Duck Under", "Ankle Pick"],
    archetypeSynergies: ["Wrestler", "Back Hunter", "Guard Player"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 2,
    unlockTier: "Base",
    notes: "Low-risk control builder that should feed chains instead of scoring directly."
  },
  {
    id: "collar-tie",
    name: "Collar Tie",
    category: "Standing",
    subcategory: "Hand Fighting",
    worksFrom: ["Standing"],
    leadsTo: ["Snapdown", "Duck Under", "Ankle Pick", "Front Headlock"],
    counters: ["Inside Tie", "Arm Drag", "Posture"],
    followUps: ["Snapdown", "Knee Tap", "Single Leg"],
    archetypeSynergies: ["Wrestler", "Pressure Passer", "Back Hunter"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 2,
    unlockTier: "Base",
    notes: "A posture-control setup. It should make front headlock routes more dangerous."
  },
  {
    id: "inside-tie",
    name: "Inside Tie",
    category: "Standing",
    subcategory: "Hand Fighting",
    worksFrom: ["Standing", "Collar Tie"],
    leadsTo: ["Body Lock", "Knee Tap", "Single Leg"],
    counters: ["Pummel", "Snapdown", "Arm Drag"],
    followUps: ["Knee Tap", "Body Lock Trip"],
    archetypeSynergies: ["Wrestler", "Pressure Passer"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 2,
    unlockTier: "Base",
    notes: "A clinch connector that can bridge wrestling and pressure passing."
  },
  {
    id: "pummeling",
    name: "Pummeling",
    category: "Standing",
    subcategory: "Hand Fighting",
    worksFrom: ["Standing", "Collar Tie", "Inside Tie", "Body Lock"],
    leadsTo: ["Underhook", "Overhook", "Body Lock"],
    counters: ["Snapdown", "Duck Under", "Throw By"],
    followUps: ["Body Lock Trip", "Inside Trip", "Hip Toss"],
    archetypeSynergies: ["Wrestler", "Pressure Passer"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 2,
    unlockTier: "Base",
    notes: "A neutral clinch battle that can decide who gets the dominant tie."
  },
  {
    id: "underhook",
    name: "Underhook",
    category: "Standing",
    subcategory: "Clinch Control",
    worksFrom: ["Standing", "Pummeling", "Half Guard"],
    leadsTo: ["Body Lock", "Knee Tap", "Back Take"],
    counters: ["Whizzer", "Pummel", "Snapdown"],
    followUps: ["Knee Tap", "Body Lock Trip", "Duck Under"],
    archetypeSynergies: ["Wrestler", "Pressure Passer", "Back Hunter"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 2,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Strong positional control. Useful in both standing and half guard layers."
  },
  {
    id: "whizzer",
    name: "Whizzer",
    category: "Standing",
    subcategory: "Counter",
    worksFrom: ["Standing", "Single Leg Entry", "Body Lock"],
    leadsTo: ["Sprawl", "Front Headlock", "Hip Toss"],
    counters: ["Shelf Single", "Run The Pipe", "Back Take"],
    followUps: ["Hip Toss", "Sprawl", "Snapdown"],
    archetypeSynergies: ["Wrestler", "Back Hunter"],
    raritySuggestion: "Rare",
    staminaSuggestion: 1,
    riskLevel: 2,
    rewardLevel: 3,
    unlockTier: "Early",
    notes: "Defensive overhook that can become offense if timed well."
  },
  {
    id: "arm-drag-standing",
    name: "Standing Arm Drag",
    category: "Standing",
    subcategory: "Setup",
    worksFrom: ["Standing", "Wrist Control", "Collar Tie"],
    leadsTo: ["Back Take", "Single Leg", "Body Lock"],
    counters: ["Square Up", "Post", "Pull Back"],
    followUps: ["Duck Under", "Mat Return", "Rear Naked Choke"],
    archetypeSynergies: ["Back Hunter", "Wrestler", "Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "Outside hand controls wrist; inside hand cups tricep and pulls across."
  },
  {
    id: "snapdown",
    name: "Snapdown",
    category: "Standing",
    subcategory: "Setup",
    worksFrom: ["Standing", "Collar Tie"],
    leadsTo: ["Front Headlock", "Guillotine", "Anaconda", "Go Behind"],
    counters: ["Posture", "Hand Fight", "Shot Under"],
    followUps: ["Front Headlock Pressure", "D'Arce Choke", "Anaconda Choke"],
    archetypeSynergies: ["Wrestler", "Back Hunter"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "Breaks posture. Should become a major combo starter."
  },
  {
    id: "level-change",
    name: "Level Change",
    category: "Standing",
    subcategory: "Setup",
    worksFrom: ["Standing", "Collar Tie", "Wrist Control"],
    leadsTo: ["Double Leg Entry", "Single Leg Entry", "High Crotch"],
    counters: ["Sprawl", "Snapdown", "Underhook"],
    followUps: ["Double Leg", "Single Leg", "Ankle Pick"],
    archetypeSynergies: ["Wrestler"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "A shot setup, not a scoring move by itself."
  },
  {
    id: "double-leg",
    name: "Double Leg",
    category: "Takedown",
    subcategory: "Shot",
    worksFrom: ["Standing", "Level Change", "Collar Tie"],
    leadsTo: ["Top Half Guard", "Top Guard", "Side Control"],
    counters: ["Sprawl", "Guillotine", "Whizzer"],
    followUps: ["Knee Slice", "Body Lock Pass", "Mount"],
    archetypeSynergies: ["Wrestler"],
    raritySuggestion: "Epic",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "High-value takedown that should be punishable by sprawl or guillotine."
  },
  {
    id: "blast-double",
    name: "Blast Double",
    category: "Takedown",
    subcategory: "Power Shot",
    worksFrom: ["Standing", "Level Change"],
    leadsTo: ["Side Control", "Top Half Guard"],
    counters: ["Sprawl", "Guillotine", "Lateral Step"],
    followUps: ["Mount", "Arm Triangle", "Pressure"],
    archetypeSynergies: ["Wrestler"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 4,
    riskLevel: 4,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "End-path wrestler finisher. Big swing, big stamina cost."
  },
  {
    id: "single-leg",
    name: "Single Leg",
    category: "Takedown",
    subcategory: "Shot",
    worksFrom: ["Standing", "Level Change", "Arm Drag"],
    leadsTo: ["Top Half Guard", "Top Guard", "Ashi Garami"],
    counters: ["Whizzer", "Sprawl", "Crossface"],
    followUps: ["Run The Pipe", "Tree Top", "Body Lock Pass"],
    archetypeSynergies: ["Wrestler", "Leg Locker", "Back Hunter"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "Flexible takedown that can chain into wrestling or leg entanglements."
  },
  {
    id: "high-crotch",
    name: "High Crotch",
    category: "Takedown",
    subcategory: "Shot",
    worksFrom: ["Standing", "Level Change"],
    leadsTo: ["Double Leg", "Tree Top", "Top Half Guard"],
    counters: ["Sprawl", "Whizzer", "Front Headlock"],
    followUps: ["Double Leg", "Single Leg", "Mat Return"],
    archetypeSynergies: ["Wrestler"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Bridge between single and double leg chains."
  },
  {
    id: "ankle-pick",
    name: "Ankle Pick",
    category: "Takedown",
    subcategory: "Off-Balance",
    worksFrom: ["Standing", "Collar Tie", "Wrist Control"],
    leadsTo: ["Top Guard", "Top Half Guard"],
    counters: ["Pull Leg Back", "Posture", "Sprawl"],
    followUps: ["Torreando Pass", "Leg Drag", "Knee Slice"],
    archetypeSynergies: ["Wrestler", "Pressure Passer"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 3,
    unlockTier: "Early",
    notes: "Good as a control-based takedown with lower finish risk."
  },
  {
    id: "knee-tap",
    name: "Knee Tap",
    category: "Takedown",
    subcategory: "Clinch",
    worksFrom: ["Standing", "Underhook", "Inside Tie"],
    leadsTo: ["Top Half Guard", "Side Control"],
    counters: ["Whizzer", "Hip Back", "Pummel"],
    followUps: ["Knee Slice", "Pressure", "Mount"],
    archetypeSynergies: ["Wrestler", "Pressure Passer"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Underhook takedown that should reward prior clinch control."
  },
  {
    id: "body-lock-trip",
    name: "Body Lock Trip",
    category: "Takedown",
    subcategory: "Clinch",
    worksFrom: ["Standing", "Body Lock", "Pummeling"],
    leadsTo: ["Side Control", "Top Half Guard"],
    counters: ["Whizzer", "Frame", "Hip Toss"],
    followUps: ["Body Lock Pass", "Mount", "Arm Triangle"],
    archetypeSynergies: ["Wrestler", "Pressure Passer"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Strong clinch takedown that feeds pressure passers."
  },
  {
    id: "inside-trip",
    name: "Inside Trip",
    category: "Takedown",
    subcategory: "Trip",
    worksFrom: ["Standing", "Body Lock", "Inside Tie"],
    leadsTo: ["Top Guard", "Top Half Guard"],
    counters: ["Base Wide", "Whizzer", "Hip Back"],
    followUps: ["Knee Slice", "Body Lock Pass"],
    archetypeSynergies: ["Wrestler", "Pressure Passer"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 3,
    unlockTier: "Early",
    notes: "A lower-cost trip that should reward clinch entries."
  },
  {
    id: "outside-trip",
    name: "Outside Trip",
    category: "Takedown",
    subcategory: "Trip",
    worksFrom: ["Standing", "Body Lock", "Overhook"],
    leadsTo: ["Side Control", "Top Half Guard"],
    counters: ["Step Out", "Whizzer", "Balance"],
    followUps: ["Mount", "Knee On Belly", "Pressure"],
    archetypeSynergies: ["Wrestler", "Pressure Passer"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Big positional reward if the clinch is already won."
  },
  {
    id: "duck-under",
    name: "Duck Under",
    category: "Takedown",
    subcategory: "Back Take",
    worksFrom: ["Standing", "Collar Tie", "Arm Drag"],
    leadsTo: ["Back Control", "Mat Return", "Rear Naked Choke"],
    counters: ["Square Up", "Whizzer", "Hip Switch"],
    followUps: ["Mat Return", "Seatbelt Control", "RNC"],
    archetypeSynergies: ["Back Hunter", "Wrestler"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Back hunter bridge from standing hand fighting to finish chains."
  },
  {
    id: "mat-return",
    name: "Mat Return",
    category: "Takedown",
    subcategory: "Back Control",
    worksFrom: ["Back Body Lock", "Duck Under", "Rear Clinch"],
    leadsTo: ["Top Turtle", "Back Control", "Side Control"],
    counters: ["Hand Fight", "Hip Heist", "Granby"],
    followUps: ["Back Control", "Seatbelt Control", "RNC"],
    archetypeSynergies: ["Wrestler", "Back Hunter"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "End-path wrestling/back control payoff."
  },
  {
    id: "hip-toss",
    name: "Hip Toss",
    category: "Throw",
    subcategory: "Hip Throw",
    worksFrom: ["Standing", "Overhook", "Body Lock"],
    leadsTo: ["Side Control", "Mount"],
    counters: ["Back Take", "Hip Block", "Base Out"],
    followUps: ["Mount", "Arm Triangle", "Kimura"],
    archetypeSynergies: ["Wrestler", "Pressure Passer"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 4,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Explosive throw. Fun as a rare big-moment card."
  },
  {
    id: "suplex",
    name: "Suplex",
    category: "Throw",
    subcategory: "Big Throw",
    worksFrom: ["Back Body Lock", "Body Lock"],
    leadsTo: ["Side Control", "Top Half Guard"],
    counters: ["Hand Fight", "Hip Drop", "Whizzer"],
    followUps: ["Pressure", "Mount", "Arm Triangle"],
    archetypeSynergies: ["Wrestler"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 4,
    riskLevel: 5,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Legendary wrestler card. Should be dramatic and expensive."
  },
  {
    id: "firemans-carry",
    name: "Fireman's Carry",
    category: "Throw",
    subcategory: "Sacrifice Throw",
    worksFrom: ["Standing", "Wrist Control", "Inside Tie"],
    leadsTo: ["Side Control", "Top Turtle"],
    counters: ["Sprawl", "Go Behind", "Front Headlock"],
    followUps: ["Side Control", "Knee On Belly", "Back Control"],
    archetypeSynergies: ["Wrestler"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 4,
    rewardLevel: 4,
    unlockTier: "Late",
    notes: "High-risk throw with strong style identity."
  },
  {
    id: "guard-pull",
    name: "Guard Pull",
    category: "Guard",
    subcategory: "Entry",
    worksFrom: ["Standing", "Collar Tie", "Wrist Control"],
    leadsTo: ["Closed Guard", "Open Guard", "Butterfly Guard"],
    counters: ["Immediate Pass", "Torreando", "Leg Drag"],
    followUps: ["Triangle", "Armbar", "Hip Bump Sweep"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 2,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "No score, but opens bottom offense."
  },
  {
    id: "closed-guard",
    name: "Closed Guard",
    category: "Guard",
    subcategory: "Position",
    worksFrom: ["Guard Pull", "Bottom Guard", "Reguard"],
    leadsTo: ["Armbar From Closed Guard", "Triangle From Closed Guard", "Kimura From Closed Guard", "Flower Sweep"],
    counters: ["Posture", "Standing Guard Break", "Knee In Tailbone"],
    followUps: ["Hip Bump Sweep", "Scissor Sweep", "Guillotine"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Common",
    staminaSuggestion: 0,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Classic bottom control position. Should support many card variants."
  },
  {
    id: "open-guard",
    name: "Open Guard",
    category: "Guard",
    subcategory: "Position",
    worksFrom: ["Guard Pull", "Closed Guard Opened", "Reguard"],
    leadsTo: ["Tripod Sweep", "De La Riva", "Spider Guard", "Ashi Garami"],
    counters: ["Torreando", "Leg Drag", "Knee Slice"],
    followUps: ["Arm Drag", "Ashi Garami Entry", "Tripod Sweep"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Common",
    staminaSuggestion: 0,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Base",
    notes: "Broad guard hub for future expansion."
  },
  {
    id: "butterfly-guard",
    name: "Butterfly Guard",
    category: "Guard",
    subcategory: "Seated Guard",
    worksFrom: ["Open Guard", "Bottom Guard", "Seated Guard"],
    leadsTo: ["Butterfly Sweep", "Arm Drag", "Ashi Garami"],
    counters: ["Body Lock Pass", "Smash Pass", "Sprawl Hips"],
    followUps: ["Butterfly Sweep", "Single Leg X", "Guillotine"],
    archetypeSynergies: ["Guard Player", "Leg Locker", "Back Hunter"],
    raritySuggestion: "Rare",
    staminaSuggestion: 1,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "Seated guard hub for sweeps, back takes, and leg entries."
  },
  {
    id: "half-guard-bottom",
    name: "Bottom Half Guard",
    category: "Guard",
    subcategory: "Position",
    worksFrom: ["Bottom Guard", "Mounted Escape", "Under Side Control"],
    leadsTo: ["Old School Sweep", "Underhook", "Reguard", "Ashi Garami"],
    counters: ["Crossface", "Knee Slice", "Backstep Pass"],
    followUps: ["Old School Sweep", "Underhook", "Reguard"],
    archetypeSynergies: ["Guard Player", "Leg Locker", "Wrestler"],
    raritySuggestion: "Common",
    staminaSuggestion: 0,
    riskLevel: 3,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Defensive but active. Should be dangerous if underhook is won."
  },
  {
    id: "half-guard-top",
    name: "Top Half Guard",
    category: "Passing",
    subcategory: "Position",
    worksFrom: ["Double Leg", "Single Leg", "Top Guard"],
    leadsTo: ["Knee Slice", "Backstep Pass", "Body Lock Pass"],
    counters: ["Underhook", "Old School Sweep", "Lockdown"],
    followUps: ["Knee Slice", "Shoulder Pressure", "Kimura"],
    archetypeSynergies: ["Pressure Passer", "Wrestler"],
    raritySuggestion: "Common",
    staminaSuggestion: 0,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Base",
    notes: "Key top-control hub after takedowns."
  },
  {
    id: "de-la-riva",
    name: "De La Riva Guard",
    category: "Guard",
    subcategory: "Open Guard",
    worksFrom: ["Open Guard"],
    leadsTo: ["De La Riva Sweep", "Back Take", "Single Leg X"],
    counters: ["Leg Pummel", "Knee Cut", "Pant Grip Break"],
    followUps: ["Back Take", "Tripod Sweep", "Ashi Garami"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Rare",
    staminaSuggestion: 1,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Future advanced guard path."
  },
  {
    id: "spider-guard",
    name: "Spider Guard",
    category: "Guard",
    subcategory: "Open Guard",
    worksFrom: ["Open Guard"],
    leadsTo: ["Triangle", "Omoplata", "Sweep"],
    counters: ["Posture Up", "Elbow Peel", "Leg Drag"],
    followUps: ["Triangle From Spider", "Omoplata", "Balloon Sweep"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Sleeve-control guard with strong triangle/omoplata links."
  },
  {
    id: "lasso-guard",
    name: "Lasso Guard",
    category: "Guard",
    subcategory: "Open Guard",
    worksFrom: ["Open Guard", "Spider Guard"],
    leadsTo: ["Triangle", "Omoplata", "Sweep"],
    counters: ["Strip Sleeve Grip", "Backstep", "Knee Pin"],
    followUps: ["Omoplata", "Triangle", "Technical Stand Up"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Control guard that can slow passers and create traps."
  },
  {
    id: "x-guard",
    name: "X-Guard",
    category: "Guard",
    subcategory: "Open Guard",
    worksFrom: ["Open Guard", "Single Leg X"],
    leadsTo: ["Technical Stand Up", "Sweep", "Back Take"],
    counters: ["Backstep", "Hip Smash", "Foot Peel"],
    followUps: ["Technical Stand Up Sweep", "Ashi Garami", "Back Take"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Epic",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Advanced guard hub for sweeps and leg locks."
  },
  {
    id: "single-leg-x",
    name: "Single Leg X",
    category: "Leg Locks",
    subcategory: "Entry Position",
    worksFrom: ["Open Guard", "Butterfly Guard", "De La Riva"],
    leadsTo: ["Ashi Garami", "Straight Ankle Lock", "Sweep"],
    counters: ["Foot Peel", "Backstep", "Hip Smash"],
    followUps: ["Ashi Garami", "Straight Ankle Lock", "Technical Stand Up"],
    archetypeSynergies: ["Leg Locker", "Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Important bridge between guard and leg attacks."
  },
  {
    id: "knee-slice",
    name: "Knee Slice Pass",
    category: "Passing",
    subcategory: "Pass",
    worksFrom: ["Top Half Guard", "Top Guard"],
    leadsTo: ["Side Control", "Knee On Belly", "Mount"],
    counters: ["Frame", "Underhook", "Reguard"],
    followUps: ["Side Control", "Mount", "Arm Triangle"],
    archetypeSynergies: ["Pressure Passer", "Wrestler"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "Core passing card. Should be strong but counterable by frames."
  },
  {
    id: "torreando-pass",
    name: "Torreando Pass",
    category: "Passing",
    subcategory: "Pass",
    worksFrom: ["Top Guard", "Open Guard"],
    leadsTo: ["Side Control", "Knee On Belly"],
    counters: ["Reguard", "Grip Break", "Sit Up Guard"],
    followUps: ["Side Control", "Knee On Belly", "Mount"],
    archetypeSynergies: ["Pressure Passer"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "Bullfighter pass. Best as an open guard answer."
  },
  {
    id: "leg-drag",
    name: "Leg Drag",
    category: "Passing",
    subcategory: "Pass",
    worksFrom: ["Top Guard", "Open Guard", "Top Half Guard"],
    leadsTo: ["Side Control", "Back Exposure", "Mount"],
    counters: ["Hip Escape", "Frame", "Invert"],
    followUps: ["Back Take", "Side Control", "Mount"],
    archetypeSynergies: ["Pressure Passer", "Back Hunter"],
    raritySuggestion: "Epic",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Pass/back-take hybrid. Great for combo gameplay."
  },
  {
    id: "body-lock-pass",
    name: "Body Lock Pass",
    category: "Passing",
    subcategory: "Pressure Pass",
    worksFrom: ["Top Guard", "Top Half Guard", "Butterfly Guard"],
    leadsTo: ["Side Control", "Mount"],
    counters: ["Frame", "Butterfly Hook", "Guillotine"],
    followUps: ["Shoulder Pressure", "Mount", "Arm Triangle"],
    archetypeSynergies: ["Pressure Passer", "Wrestler"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Expensive but identity-defining pressure pass."
  },
  {
    id: "backstep-pass",
    name: "Backstep Pass",
    category: "Passing",
    subcategory: "Half Guard Pass",
    worksFrom: ["Top Half Guard"],
    leadsTo: ["Side Control", "Leg Drag"],
    counters: ["Underhook", "Take The Back", "Reguard"],
    followUps: ["Side Control", "Leg Drag", "Kimura"],
    archetypeSynergies: ["Pressure Passer", "Leg Locker"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Half guard answer that can expose leg lock counters later."
  },
  {
    id: "smash-pass",
    name: "Smash Pass",
    category: "Passing",
    subcategory: "Pressure Pass",
    worksFrom: ["Top Guard", "Open Guard", "Butterfly Guard"],
    leadsTo: ["Side Control", "Mount"],
    counters: ["Frame", "Hip Escape", "Underhook"],
    followUps: ["Shoulder Pressure", "Mount", "Kimura"],
    archetypeSynergies: ["Pressure Passer"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Heavy passer route; should drain stamina or build control."
  },
  {
    id: "knee-on-belly",
    name: "Knee On Belly",
    category: "Pins",
    subcategory: "Control Position",
    worksFrom: ["Side Control", "Torreando Pass", "Knee Slice"],
    leadsTo: ["Mount", "Armbar", "Kimura", "Baseball Choke"],
    counters: ["Hip Escape", "Frame", "Reguard"],
    followUps: ["Mount", "Armbar", "Pressure"],
    archetypeSynergies: ["Pressure Passer", "Back Hunter"],
    raritySuggestion: "Rare",
    staminaSuggestion: 1,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Mobile pin between side control and mount."
  },
  {
    id: "side-control",
    name: "Side Control",
    category: "Pins",
    subcategory: "Control Position",
    worksFrom: ["Pass", "Throw", "Sweep"],
    leadsTo: ["Mount", "Knee On Belly", "Kimura", "Arm Triangle", "North South"],
    counters: ["Hip Escape", "Frame", "Ghost Escape"],
    followUps: ["Mount", "Kimura", "North South Choke"],
    archetypeSynergies: ["Pressure Passer", "Back Hunter"],
    raritySuggestion: "Common",
    staminaSuggestion: 0,
    riskLevel: 1,
    rewardLevel: 4,
    unlockTier: "Base",
    notes: "Dominant hub. Needs escape/counterplay so it does not feel final."
  },
  {
    id: "mount",
    name: "Mount",
    category: "Pins",
    subcategory: "Dominant Position",
    worksFrom: ["Side Control", "Knee On Belly", "Sweep"],
    leadsTo: ["Armbar From Mount", "Arm Triangle", "Back Take", "Mounted Triangle"],
    counters: ["Bridge Escape", "Elbow Escape", "Kipping Escape"],
    followUps: ["Armbar", "Arm Triangle", "Pressure"],
    archetypeSynergies: ["Pressure Passer", "Guard Player"],
    raritySuggestion: "Rare",
    staminaSuggestion: 0,
    riskLevel: 1,
    rewardLevel: 5,
    unlockTier: "Early",
    notes: "Dominant scoring/control position with multiple finishes."
  },
  {
    id: "back-control",
    name: "Back Control",
    category: "Pins",
    subcategory: "Dominant Position",
    worksFrom: ["Arm Drag", "Duck Under", "Back Take", "Scramble"],
    leadsTo: ["Rear Naked Choke", "Bow And Arrow", "Armbar From Back"],
    counters: ["Hand Fight", "Back Escape", "Turn In"],
    followUps: ["Seatbelt Control", "RNC", "Bow And Arrow"],
    archetypeSynergies: ["Back Hunter", "Wrestler"],
    raritySuggestion: "Epic",
    staminaSuggestion: 0,
    riskLevel: 1,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Highest-value control position for back hunter."
  },
  {
    id: "turtle",
    name: "Turtle",
    category: "Scramble",
    subcategory: "Defensive Position",
    worksFrom: ["Sprawl", "Technical Bridge", "Front Headlock", "Failed Shot"],
    leadsTo: ["Back Control", "Front Headlock", "Guard Recovery", "Stand Up"],
    counters: ["Hooks", "Seatbelt", "Clock Choke"],
    followUps: ["Granby", "Sit Out", "Single Leg"],
    archetypeSynergies: ["Back Hunter", "Wrestler"],
    raritySuggestion: "Common",
    staminaSuggestion: 0,
    riskLevel: 4,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Danger/scramble position. Should invite back attacks and escapes."
  },
  {
    id: "north-south",
    name: "North South",
    category: "Pins",
    subcategory: "Control Position",
    worksFrom: ["Side Control", "Sprawl"],
    leadsTo: ["North South Choke", "Kimura", "Side Control"],
    counters: ["Frame", "Turn In", "Reguard"],
    followUps: ["Kimura", "North South Choke", "Side Control"],
    archetypeSynergies: ["Pressure Passer"],
    raritySuggestion: "Rare",
    staminaSuggestion: 1,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Optional control hub for kimura and choke branches."
  },
  {
    id: "front-headlock",
    name: "Front Headlock",
    category: "Pins",
    subcategory: "Control Position",
    worksFrom: ["Snapdown", "Sprawl", "Failed Shot"],
    leadsTo: ["Guillotine", "D'Arce", "Anaconda", "Go Behind"],
    counters: ["Hand Fight", "Posture", "Peek Out"],
    followUps: ["Headlock Pressure", "Guillotine", "Anaconda"],
    archetypeSynergies: ["Wrestler", "Back Hunter"],
    raritySuggestion: "Rare",
    staminaSuggestion: 0,
    riskLevel: 2,
    rewardLevel: 5,
    unlockTier: "Early",
    notes: "Major wrestler/back hunter finish hub."
  },
  {
    id: "bridge-escape",
    name: "Bridge Escape",
    category: "Escapes",
    subcategory: "Mount Escape",
    worksFrom: ["Mounted"],
    leadsTo: ["Bottom Half Guard", "Top Guard", "Scramble"],
    counters: ["Post Hand", "High Mount", "Technical Mount"],
    followUps: ["Reguard", "Technical Bridge", "Frame"],
    archetypeSynergies: ["Wrestler", "Guard Player"],
    raritySuggestion: "Common",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Explosive mount escape. Should have timing/counterplay."
  },
  {
    id: "elbow-escape",
    name: "Elbow Escape",
    category: "Escapes",
    subcategory: "Mount Escape",
    worksFrom: ["Mounted"],
    leadsTo: ["Bottom Half Guard", "Bottom Guard"],
    counters: ["Crossface", "Mount Pressure", "Grape Vine"],
    followUps: ["Reguard", "Frame", "Hip Escape"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Common",
    staminaSuggestion: 2,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Technical mount escape and key defensive card."
  },
  {
    id: "hip-escape",
    name: "Hip Escape",
    category: "Escapes",
    subcategory: "Pin Escape",
    worksFrom: ["Mounted", "Under Side Control", "Bottom Half Guard", "Caught Ashi Garami"],
    leadsTo: ["Bottom Half Guard", "Bottom Guard", "Open Guard"],
    counters: ["Pressure", "Leg Drag", "Knee On Belly"],
    followUps: ["Reguard", "Frame", "Ashi Garami Entry"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Universal movement card."
  },
  {
    id: "reguard",
    name: "Reguard",
    category: "Escapes",
    subcategory: "Guard Recovery",
    worksFrom: ["Bottom Half Guard", "Under Side Control", "Turtle"],
    leadsTo: ["Bottom Guard", "Open Guard", "Butterfly Guard"],
    counters: ["Pressure", "Leg Drag", "Knee Slice"],
    followUps: ["Guard Pull", "Triangle", "Ashi Garami Entry"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Common",
    staminaSuggestion: 2,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Stops runaway top pressure."
  },
  {
    id: "ghost-escape",
    name: "Ghost Escape",
    category: "Escapes",
    subcategory: "Side Control Escape",
    worksFrom: ["Under Side Control"],
    leadsTo: ["Turtle", "Back Take", "Guard"],
    counters: ["Chest Pressure", "Hip Follow", "Head Control"],
    followUps: ["Turtle", "Single Leg", "Back Take"],
    archetypeSynergies: ["Back Hunter", "Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Flashy escape that can become offense."
  },
  {
    id: "technical-bridge",
    name: "Technical Bridge",
    category: "Escapes",
    subcategory: "Scramble Escape",
    worksFrom: ["Mounted", "Under Side Control"],
    leadsTo: ["Turtle", "Standing", "Single Leg"],
    counters: ["Back Take", "Seatbelt", "Front Headlock"],
    followUps: ["Stand Up", "Single Leg", "Reguard"],
    archetypeSynergies: ["Back Hunter", "Wrestler"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Escape that creates scramble tension."
  },
  {
    id: "hip-bump-sweep",
    name: "Hip Bump Sweep",
    category: "Sweeps",
    subcategory: "Closed Guard",
    worksFrom: ["Closed Guard", "Bottom Guard"],
    leadsTo: ["Mount", "Top Guard"],
    counters: ["Post Hand", "Posture", "Kimura Counter"],
    followUps: ["Mount", "Armbar", "Kimura"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "Explosive closed guard sweep that can chain into attacks."
  },
  {
    id: "scissor-sweep",
    name: "Scissor Sweep",
    category: "Sweeps",
    subcategory: "Closed Guard",
    worksFrom: ["Closed Guard", "Bottom Guard"],
    leadsTo: ["Top Guard", "Mount"],
    counters: ["Base Wide", "Posture", "Step Over"],
    followUps: ["Knee Slice", "Mount", "Armbar"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "Classic lever sweep."
  },
  {
    id: "flower-sweep",
    name: "Flower Sweep",
    category: "Sweeps",
    subcategory: "Closed Guard",
    worksFrom: ["Closed Guard", "Bottom Guard"],
    leadsTo: ["Mount"],
    counters: ["Posture", "Base", "Hand Post"],
    followUps: ["Mount", "Armbar From Mount", "Arm Triangle"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 5,
    unlockTier: "Early",
    notes: "High-value sweep to mount."
  },
  {
    id: "butterfly-sweep",
    name: "Butterfly Sweep",
    category: "Sweeps",
    subcategory: "Butterfly Guard",
    worksFrom: ["Butterfly Guard", "Bottom Guard"],
    leadsTo: ["Top Half Guard", "Top Guard", "Ashi Garami"],
    counters: ["Post Hand", "Sprawl Hips", "Body Lock"],
    followUps: ["Ashi Garami Entry", "Knee Slice", "Pressure"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Seated guard sweep that can branch into passing or legs."
  },
  {
    id: "old-school-sweep",
    name: "Old School Sweep",
    category: "Sweeps",
    subcategory: "Half Guard",
    worksFrom: ["Bottom Half Guard"],
    leadsTo: ["Top Half Guard", "Top Guard"],
    counters: ["Crossface", "Whizzer", "Sprawl"],
    followUps: ["Knee Slice", "Body Lock Pass", "Ashi Garami"],
    archetypeSynergies: ["Guard Player", "Leg Locker", "Wrestler"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Half guard underhook reward."
  },
  {
    id: "tripod-sweep",
    name: "Tripod Sweep",
    category: "Sweeps",
    subcategory: "Open Guard",
    worksFrom: ["Open Guard"],
    leadsTo: ["Top Guard", "Standing"],
    counters: ["Break Grips", "Step Back", "Knee Cut"],
    followUps: ["Technical Stand Up", "Torreando", "Leg Drag"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Open guard off-balance sweep."
  },
  {
    id: "de-la-riva-sweep",
    name: "De La Riva Sweep",
    category: "Sweeps",
    subcategory: "Open Guard",
    worksFrom: ["De La Riva Guard"],
    leadsTo: ["Top Guard", "Back Take", "Single Leg X"],
    counters: ["Leg Pummel", "Backstep", "Grip Break"],
    followUps: ["Back Take", "Ashi Garami", "Top Guard"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Advanced open guard sweep for future expansion."
  },
  {
    id: "armbar-closed-guard",
    name: "Armbar From Closed Guard",
    category: "Submissions",
    subcategory: "Arm Lock",
    worksFrom: ["Closed Guard", "Bottom Guard"],
    leadsTo: ["Tapout"],
    counters: ["Posture", "Stack", "Elbow Pull"],
    followUps: ["Triangle", "Omoplata", "Sweep"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Classic guard finish. Should chain with triangle/omoplata."
  },
  {
    id: "armbar-mount",
    name: "Armbar From Mount",
    category: "Submissions",
    subcategory: "Arm Lock",
    worksFrom: ["Mount"],
    leadsTo: ["Tapout"],
    counters: ["Elbow Hide", "Stack", "Hitchhiker Escape"],
    followUps: ["Triangle From Mount", "Back Take", "S-Mount"],
    archetypeSynergies: ["Pressure Passer", "Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Dominant-position armbar."
  },
  {
    id: "armbar-back",
    name: "Armbar From Back Control",
    category: "Submissions",
    subcategory: "Arm Lock",
    worksFrom: ["Back Control"],
    leadsTo: ["Tapout"],
    counters: ["Hand Fight", "Elbow Hide", "Turn In"],
    followUps: ["RNC", "Triangle From Back"],
    archetypeSynergies: ["Back Hunter"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Back-control secondary finish."
  },
  {
    id: "flying-armbar",
    name: "Flying Armbar",
    category: "Submissions",
    subcategory: "Flying Attack",
    worksFrom: ["Standing", "Collar Tie", "Wrist Control"],
    leadsTo: ["Tapout", "Bottom Guard"],
    counters: ["Posture", "Slam Defense", "Pull Arm Free"],
    followUps: ["Armbar", "Triangle", "Guard"],
    archetypeSynergies: ["Guard Player", "Back Hunter"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 4,
    riskLevel: 5,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Collector-style legendary. Must be high-risk."
  },
  {
    id: "triangle-closed-guard",
    name: "Triangle From Closed Guard",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["Closed Guard", "Bottom Guard"],
    leadsTo: ["Tapout"],
    counters: ["Posture", "Stack", "Shoulder Angle"],
    followUps: ["Armbar", "Omoplata", "Triangle Sweep"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Early",
    notes: "Core guard-player finish."
  },
  {
    id: "triangle-mount",
    name: "Mounted Triangle",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["Mount"],
    leadsTo: ["Tapout"],
    counters: ["Frame Hips", "Posture", "Elbow Position"],
    followUps: ["Armbar", "Mounted Armbar"],
    archetypeSynergies: ["Guard Player", "Pressure Passer"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 4,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Advanced mount finish."
  },
  {
    id: "flying-triangle",
    name: "Flying Triangle",
    category: "Submissions",
    subcategory: "Flying Attack",
    worksFrom: ["Standing", "Collar Tie", "Wrist Control"],
    leadsTo: ["Tapout", "Bottom Guard"],
    counters: ["Posture", "Step Away", "Stack"],
    followUps: ["Triangle", "Armbar", "Guard"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 4,
    riskLevel: 5,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Flashy collectible finish. Needs major miss penalty."
  },
  {
    id: "guillotine-standing",
    name: "Standing Guillotine",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["Standing", "Front Headlock", "Snapdown"],
    leadsTo: ["Tapout", "Bottom Guard", "Front Headlock"],
    counters: ["Posture", "Hand Fight", "Body Lock"],
    followUps: ["Guard Pull Guillotine", "Snapdown", "Anaconda"],
    archetypeSynergies: ["Wrestler", "Guard Player", "Back Hunter"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Head trapped under armpit; choking arm under neck."
  },
  {
    id: "guillotine-guard",
    name: "Guillotine From Guard",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["Bottom Guard", "Closed Guard", "Front Headlock"],
    leadsTo: ["Tapout"],
    counters: ["Posture", "Hand Fight", "Von Flue Threat"],
    followUps: ["Sweep", "Front Headlock", "Arm-In Guillotine"],
    archetypeSynergies: ["Guard Player", "Wrestler"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Good punish for opponent driving forward."
  },
  {
    id: "rear-naked-choke",
    name: "Rear Naked Choke",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["Back Control"],
    leadsTo: ["Tapout"],
    counters: ["Protect Neck", "Two On One", "Turn In"],
    followUps: ["Hand Fight", "Armbar From Back"],
    archetypeSynergies: ["Back Hunter"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 3,
    riskLevel: 2,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Highest-percentage back finish."
  },
  {
    id: "arm-triangle",
    name: "Arm Triangle",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["Mount", "Side Control", "Top Half Guard"],
    leadsTo: ["Tapout"],
    counters: ["Frame Neck", "Answer The Phone", "Reguard"],
    followUps: ["Mount", "Side Control Pressure"],
    archetypeSynergies: ["Pressure Passer", "Wrestler"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 3,
    riskLevel: 2,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Pressure-passer finisher."
  },
  {
    id: "darce",
    name: "D'Arce Choke",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["Front Headlock", "Top Half Guard", "Side Control", "Turtle"],
    leadsTo: ["Tapout"],
    counters: ["Posture", "Hand Fight", "Roll Through"],
    followUps: ["Anaconda", "Front Headlock", "Back Take"],
    archetypeSynergies: ["Wrestler", "Back Hunter", "Pressure Passer"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Front headlock/submission bridge."
  },
  {
    id: "anaconda",
    name: "Anaconda Choke",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["Front Headlock", "Turtle"],
    leadsTo: ["Tapout"],
    counters: ["Hand Fight", "Posture", "Roll Defense"],
    followUps: ["D'Arce", "Guillotine", "Back Control"],
    archetypeSynergies: ["Wrestler", "Back Hunter"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Pairs with snapdown and front headlock control."
  },
  {
    id: "kimura-closed-guard",
    name: "Kimura From Closed Guard",
    category: "Submissions",
    subcategory: "Shoulder Lock",
    worksFrom: ["Closed Guard", "Bottom Guard"],
    leadsTo: ["Tapout", "Sweep", "Back Take"],
    counters: ["Posture", "Straighten Arm", "Grip Break"],
    followUps: ["Hip Bump Sweep", "Armbar", "Back Take"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Figure-four grip: one hand controls wrist, other reaches over to grab own wrist."
  },
  {
    id: "kimura-side-control",
    name: "Kimura From Side Control",
    category: "Submissions",
    subcategory: "Shoulder Lock",
    worksFrom: ["Side Control", "North South"],
    leadsTo: ["Tapout", "Back Take", "Armbar"],
    counters: ["Grip Fight", "Turn In", "Straighten Arm"],
    followUps: ["Armbar", "Back Take", "North South"],
    archetypeSynergies: ["Pressure Passer", "Back Hunter"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 2,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Top kimura trap can become submission or back take."
  },
  {
    id: "americana",
    name: "Americana",
    category: "Submissions",
    subcategory: "Shoulder Lock",
    worksFrom: ["Mount", "Side Control"],
    leadsTo: ["Tapout"],
    counters: ["Elbow Tight", "Bridge", "Turn Side"],
    followUps: ["Armbar", "Mount Pressure"],
    archetypeSynergies: ["Pressure Passer"],
    raritySuggestion: "Rare",
    staminaSuggestion: 3,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Beginner-friendly top pressure submission."
  },
  {
    id: "omoplata",
    name: "Omoplata",
    category: "Submissions",
    subcategory: "Shoulder Lock",
    worksFrom: ["Closed Guard", "Open Guard", "Spider Guard", "Lasso Guard"],
    leadsTo: ["Tapout", "Sweep", "Back Take"],
    counters: ["Posture", "Roll", "Step Over"],
    followUps: ["Omoplata Sweep", "Armbar", "Triangle"],
    archetypeSynergies: ["Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Guard trap with sweep/submission branches."
  },
  {
    id: "north-south-choke",
    name: "North South Choke",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["North South", "Side Control"],
    leadsTo: ["Tapout"],
    counters: ["Frame Neck", "Turn In", "Reguard"],
    followUps: ["Side Control", "Kimura"],
    archetypeSynergies: ["Pressure Passer"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 2,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Pressure choke from north south."
  },
  {
    id: "ezekiel",
    name: "Ezekiel Choke",
    category: "Submissions",
    subcategory: "Choke",
    worksFrom: ["Mount", "Top Guard", "Side Control"],
    leadsTo: ["Tapout"],
    counters: ["Frame Neck", "Posture", "Hand Fight"],
    followUps: ["Mount Pressure", "Arm Triangle"],
    archetypeSynergies: ["Pressure Passer"],
    raritySuggestion: "Rare",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Gi choke option for pressure builds."
  },
  {
    id: "bow-and-arrow",
    name: "Bow And Arrow Choke",
    category: "Submissions",
    subcategory: "Gi Choke",
    worksFrom: ["Back Control"],
    leadsTo: ["Tapout"],
    counters: ["Grip Fight", "Turn In", "Clear Hook"],
    followUps: ["RNC", "Armbar From Back"],
    archetypeSynergies: ["Back Hunter"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 4,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Late-tree gi back attack."
  },
  {
    id: "ashi-garami",
    name: "Ashi Garami",
    category: "Leg Locks",
    subcategory: "Entanglement",
    worksFrom: ["Open Guard", "Butterfly Guard", "Single Leg X", "Bottom Half Guard"],
    leadsTo: ["Straight Ankle Lock", "Heel Hook", "Sweep"],
    counters: ["Boot", "Hand Fight", "Clear Knee Line"],
    followUps: ["Straight Ankle Lock", "Technical Stand Up", "Heel Hook"],
    archetypeSynergies: ["Leg Locker", "Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Early",
    notes: "Core leg locker position. One seated, one standing leg trapped."
  },
  {
    id: "straight-ankle-lock",
    name: "Straight Ankle Lock",
    category: "Leg Locks",
    subcategory: "Submission",
    worksFrom: ["Ashi Garami", "Single Leg X"],
    leadsTo: ["Tapout"],
    counters: ["Boot", "Hand Fight", "Clear Knee Line"],
    followUps: ["Ashi Garami", "Sweep", "Heel Hook"],
    archetypeSynergies: ["Leg Locker"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 3,
    rewardLevel: 5,
    unlockTier: "Early",
    notes: "Foot trapped under armpit, forearm on Achilles, knees pinched."
  },
  {
    id: "inside-heel-hook",
    name: "Inside Heel Hook",
    category: "Leg Locks",
    subcategory: "Submission",
    worksFrom: ["Saddle", "Inside Sankaku", "Ashi Garami"],
    leadsTo: ["Tapout"],
    counters: ["Hide Heel", "Clear Knee Line", "Hand Fight"],
    followUps: ["Kneebar", "Toe Hold", "Sweep"],
    archetypeSynergies: ["Leg Locker"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 4,
    riskLevel: 5,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Late-tree dangerous leg lock. Needs ruleset/gi legality handling later."
  },
  {
    id: "outside-heel-hook",
    name: "Outside Heel Hook",
    category: "Leg Locks",
    subcategory: "Submission",
    worksFrom: ["Ashi Garami", "Outside Ashi"],
    leadsTo: ["Tapout"],
    counters: ["Hide Heel", "Roll", "Clear Knee Line"],
    followUps: ["Straight Ankle Lock", "Toe Hold"],
    archetypeSynergies: ["Leg Locker"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 4,
    riskLevel: 5,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "High-risk finish with strong collector appeal."
  },
  {
    id: "kneebar",
    name: "Kneebar",
    category: "Leg Locks",
    subcategory: "Submission",
    worksFrom: ["Ashi Garami", "Backstep", "Top Half Guard"],
    leadsTo: ["Tapout"],
    counters: ["Bend Knee", "Hand Fight", "Turn Out"],
    followUps: ["Toe Hold", "Ashi Garami"],
    archetypeSynergies: ["Leg Locker"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 4,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Straight leg-lock finisher that can emerge from top or bottom."
  },
  {
    id: "toe-hold",
    name: "Toe Hold",
    category: "Leg Locks",
    subcategory: "Submission",
    worksFrom: ["Ashi Garami", "50/50", "Open Guard"],
    leadsTo: ["Tapout"],
    counters: ["Straighten Leg", "Grip Fight", "Kick Free"],
    followUps: ["Kneebar", "Heel Hook"],
    archetypeSynergies: ["Leg Locker"],
    raritySuggestion: "Epic",
    staminaSuggestion: 3,
    riskLevel: 4,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Rotational foot lock for advanced leg trees."
  },
  {
    id: "imanari-roll",
    name: "Imanari Roll",
    category: "Leg Locks",
    subcategory: "Flying Entry",
    worksFrom: ["Standing"],
    leadsTo: ["Ashi Garami", "Heel Hook"],
    counters: ["Step Back", "Sprawl", "Leg Drag"],
    followUps: ["Inside Heel Hook", "Ashi Garami", "Sweep"],
    archetypeSynergies: ["Leg Locker"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 4,
    riskLevel: 5,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Legendary leg-lock entry. Very fun, very risky."
  },
  {
    id: "saddle",
    name: "Saddle / Inside Sankaku",
    category: "Leg Locks",
    subcategory: "Entanglement",
    worksFrom: ["Ashi Garami", "Backstep", "Knee Shield"],
    leadsTo: ["Inside Heel Hook", "Kneebar", "Toe Hold"],
    counters: ["Clear Knee Line", "Hand Fight", "Hide Heel"],
    followUps: ["Inside Heel Hook", "Kneebar"],
    archetypeSynergies: ["Leg Locker"],
    raritySuggestion: "Legendary",
    staminaSuggestion: 3,
    riskLevel: 4,
    rewardLevel: 5,
    unlockTier: "Late",
    notes: "Advanced entanglement hub."
  },
  {
    id: "fifty-fifty",
    name: "50/50",
    category: "Leg Locks",
    subcategory: "Entanglement",
    worksFrom: ["Open Guard", "Ashi Garami"],
    leadsTo: ["Toe Hold", "Heel Hook", "Sweep"],
    counters: ["Stalemate", "Hand Fight", "Back Take"],
    followUps: ["Toe Hold", "Stand Up Sweep"],
    archetypeSynergies: ["Leg Locker", "Guard Player"],
    raritySuggestion: "Epic",
    staminaSuggestion: 2,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Late",
    notes: "Could create tense mirror leg-lock exchanges."
  },
  {
    id: "sprawl",
    name: "Sprawl",
    category: "Counters",
    subcategory: "Takedown Counter",
    worksFrom: ["Standing", "Opponent Shot"],
    leadsTo: ["Front Headlock", "Turtle", "Go Behind"],
    counters: ["Chain Wrestling", "Reshot", "Pull Guard"],
    followUps: ["Snapdown", "Front Headlock", "Back Take"],
    archetypeSynergies: ["Wrestler", "Back Hunter"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 4,
    unlockTier: "Base",
    notes: "Counter card that should punish predictable takedowns."
  },
  {
    id: "frame",
    name: "Frame",
    category: "Counters",
    subcategory: "Pressure Counter",
    worksFrom: ["Bottom Guard", "Bottom Half Guard", "Under Side Control", "Mounted"],
    leadsTo: ["Hip Escape", "Reguard", "Counter Sweep"],
    counters: ["Shoulder Pressure", "Knee Slice", "Body Lock Pass"],
    followUps: ["Hip Escape", "Reguard", "Ashi Garami"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Defensive timing card that should slow passers."
  },
  {
    id: "protect-neck",
    name: "Protect Neck",
    category: "Counters",
    subcategory: "Submission Defense",
    worksFrom: ["Back Taken", "Caught Front Headlock", "Turtle"],
    leadsTo: ["Hand Fight", "Escape", "Turtle"],
    counters: ["RNC", "Guillotine", "Anaconda", "D'Arce"],
    followUps: ["Hand Fight", "Turn In", "Reguard"],
    archetypeSynergies: ["Back Hunter", "Wrestler", "Guard Player"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Should make choke battles interactive."
  },
  {
    id: "hand-fight-defense",
    name: "Hand Fight",
    category: "Counters",
    subcategory: "Grip Defense",
    worksFrom: ["Back Taken", "Caught Front Headlock", "Caught Ashi Garami", "Turtle"],
    leadsTo: ["Standing", "Guard", "Escape"],
    counters: ["RNC", "Guillotine", "Straight Ankle Lock"],
    followUps: ["Stand Up", "Reguard", "Clear Knee Line"],
    archetypeSynergies: ["Back Hunter", "Leg Locker", "Wrestler"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Universal defensive layer."
  },
  {
    id: "posture",
    name: "Posture",
    category: "Counters",
    subcategory: "Guard Defense",
    worksFrom: ["Top Guard", "Closed Guard"],
    leadsTo: ["Guard Break", "Standing Guard Break", "Torreando"],
    counters: ["Triangle", "Armbar", "Guillotine"],
    followUps: ["Standing Guard Break", "Knee Slice", "Torreando"],
    archetypeSynergies: ["Pressure Passer", "Wrestler"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Top-player defense against guard submissions."
  },
  {
    id: "standing-guard-break",
    name: "Standing Guard Break",
    category: "Transitions",
    subcategory: "Guard Break",
    worksFrom: ["Top Guard", "Closed Guard"],
    leadsTo: ["Open Guard", "Torreando", "Leg Drag"],
    counters: ["Lumberjack Sweep", "Single Leg X", "Ashi Garami"],
    followUps: ["Torreando", "Leg Drag", "Knee Slice"],
    archetypeSynergies: ["Pressure Passer"],
    raritySuggestion: "Common",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 4,
    unlockTier: "Early",
    notes: "Transitions closed guard to open passing exchange."
  },
  {
    id: "knee-in-tailbone-break",
    name: "Knee-In-Tailbone Break",
    category: "Transitions",
    subcategory: "Guard Break",
    worksFrom: ["Top Guard", "Closed Guard"],
    leadsTo: ["Open Guard", "Knee Slice"],
    counters: ["Hip Bump Sweep", "Collar Drag", "Kimura"],
    followUps: ["Knee Slice", "Torreando"],
    archetypeSynergies: ["Pressure Passer"],
    raritySuggestion: "Common",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 3,
    unlockTier: "Early",
    notes: "Basic guard break option."
  },
  {
    id: "go-behind",
    name: "Go Behind",
    category: "Transitions",
    subcategory: "Front Headlock Transition",
    worksFrom: ["Front Headlock", "Sprawl", "Turtle"],
    leadsTo: ["Back Control", "Side Control"],
    counters: ["Sit Out", "Granby", "Hand Fight"],
    followUps: ["Seatbelt Control", "RNC", "Mat Return"],
    archetypeSynergies: ["Back Hunter", "Wrestler"],
    raritySuggestion: "Rare",
    staminaSuggestion: 2,
    riskLevel: 2,
    rewardLevel: 5,
    unlockTier: "Mid",
    notes: "Position transition that turns front headlock into back exposure."
  },
  {
    id: "seatbelt-control",
    name: "Seatbelt Control",
    category: "Transitions",
    subcategory: "Back Control",
    worksFrom: ["Back Control", "Go Behind", "Turtle"],
    leadsTo: ["Rear Naked Choke", "Bow And Arrow", "Armbar From Back"],
    counters: ["Two On One", "Turn In", "Clear Hook"],
    followUps: ["RNC", "Hook Retention", "Bow And Arrow"],
    archetypeSynergies: ["Back Hunter"],
    raritySuggestion: "Rare",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 5,
    unlockTier: "Early",
    notes: "Back hunter control card."
  },
  {
    id: "hook-retention",
    name: "Hook Retention",
    category: "Transitions",
    subcategory: "Back Control",
    worksFrom: ["Back Control"],
    leadsTo: ["RNC", "Bow And Arrow", "Armbar From Back"],
    counters: ["Clear Hook", "Turn In", "Hand Fight"],
    followUps: ["Seatbelt Control", "RNC"],
    archetypeSynergies: ["Back Hunter"],
    raritySuggestion: "Rare",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Keeps back control alive; great for control/finish tension."
  },
  {
    id: "guard-retention",
    name: "Guard Retention",
    category: "Transitions",
    subcategory: "Defense",
    worksFrom: ["Bottom Guard", "Open Guard", "Under Passing"],
    leadsTo: ["Open Guard", "Closed Guard", "Butterfly Guard"],
    counters: ["Knee Slice", "Torreando", "Leg Drag"],
    followUps: ["Reguard", "Ashi Garami Entry", "Triangle"],
    archetypeSynergies: ["Guard Player", "Leg Locker"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 1,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Future defensive mechanic for guard builds."
  },
  {
    id: "technical-stand-up",
    name: "Technical Stand Up",
    category: "Transitions",
    subcategory: "Escape",
    worksFrom: ["Open Guard", "Butterfly Guard", "X-Guard", "Turtle"],
    leadsTo: ["Standing", "Single Leg", "Collar Tie"],
    counters: ["Pressure", "Snapdown", "Leg Drag"],
    followUps: ["Standing", "Single Leg", "Wrist Control"],
    archetypeSynergies: ["Wrestler", "Guard Player", "Leg Locker"],
    raritySuggestion: "Common",
    staminaSuggestion: 1,
    riskLevel: 2,
    rewardLevel: 3,
    unlockTier: "Base",
    notes: "Reset option that can prevent bad-position snowballs."
  },
  {
    id: "scramble",
    name: "Scramble",
    category: "Transitions",
    subcategory: "Neutral Chaos",
    worksFrom: ["Failed Shot", "Turtle", "Technical Bridge", "Failed Submission"],
    leadsTo: ["Standing", "Back Control", "Top Half Guard", "Front Headlock"],
    counters: ["Seatbelt", "Sprawl", "Frame"],
    followUps: ["Back Take", "Single Leg", "Reguard"],
    archetypeSynergies: ["Back Hunter", "Wrestler"],
    raritySuggestion: "Rare",
    staminaSuggestion: 1,
    riskLevel: 3,
    rewardLevel: 4,
    unlockTier: "Mid",
    notes: "Could become a momentum-swing mechanic later."
  }
];

const techniqueById = Object.fromEntries(techniqueDatabase.map((technique) => [technique.id, technique]));

const cardTechniqueMap = {
  "double-leg": "double-leg",
  "guard-pull": "guard-pull",
  sprawl: "sprawl",
  "knee-slice": "knee-slice",
  pressure: "side-control",
  "hip-escape": "hip-escape",
  bridge: "bridge-escape",
  "closed-guard-sweep": "flower-sweep",
  frame: "frame",
  armbar: "armbar-mount",
  triangle: "triangle-closed-guard",
  "rear-naked-choke": "rear-naked-choke",
  "arm-drag": "arm-drag-standing",
  reguard: "reguard",
  mount: "mount",
  "wrist-control": "wrist-control",
  "collar-tie": "collar-tie",
  snapdown: "snapdown",
  "headlock-pressure": "front-headlock",
  "slide-by": "go-behind",
  "single-leg": "single-leg",
  "body-lock": "body-lock-trip",
  "inside-trip": "inside-trip",
  "ankle-pick": "ankle-pick",
  "duck-under": "duck-under",
  "hip-toss": "hip-toss",
  torreando: "torreando-pass",
  "leg-drag": "leg-drag",
  "body-lock-pass": "body-lock-pass",
  "backstep-pass": "backstep-pass",
  "elbow-escape": "elbow-escape",
  "technical-bridge": "technical-bridge",
  "hip-bump-sweep": "hip-bump-sweep",
  "scissor-sweep": "scissor-sweep",
  "butterfly-sweep": "butterfly-sweep",
  "old-school-sweep": "old-school-sweep",
  "ashi-garami-entry": "ashi-garami",
  guillotine: "guillotine-standing",
  kimura: "kimura-side-control",
  "arm-triangle": "arm-triangle",
  darce: "darce",
  anaconda: "anaconda",
  "straight-ankle-lock": "straight-ankle-lock",
  "heel-hook": "inside-heel-hook",
  "hand-fight": "hand-fight-defense",
  "protect-neck": "protect-neck",
  "seatbelt-pressure": "seatbelt-control",
  "high-crotch": "high-crotch",
  "mat-return": "mat-return",
  "front-headlock-spin": "go-behind",
  "cow-catcher": "front-headlock",
  "firemans-carry": "firemans-carry",
  suplex: "suplex",
  "tripod-sweep": "tripod-sweep",
  "pendulum-sweep": "hip-bump-sweep",
  "lumberjack-sweep": "tripod-sweep",
  "butterfly-hooks": "butterfly-guard",
  omoplata: "omoplata",
  "omoplata-sweep": "omoplata",
  "x-pass": "torreando-pass",
  "shin-pin-pass": "knee-slice",
  "over-under-pass": "body-lock-pass",
  "smash-pass": "smash-pass",
  "knee-on-belly": "knee-on-belly",
  "north-south-control": "north-south",
  americana: "americana",
  "body-triangle": "seatbelt-control",
  "bow-and-arrow": "bow-and-arrow",
  "clock-choke": "rear-naked-choke",
  "crucifix-control": "seatbelt-control",
  "single-leg-x-entry": "single-leg-x",
  "ashi-control": "ashi-garami",
  "toe-hold": "toe-hold",
  kneebar: "kneebar",
  "leg-pummel-escape": "hand-fight-defense",
  "knee-elbow-escape": "elbow-escape",
  rest: "technical-stand-up"
};

function techniqueForCard(card) {
  return techniqueById[cardTechniqueMap[card.id]] || null;
}

function techniqueCategoryCounts() {
  return techniqueDatabase.reduce((counts, technique) => {
    counts[technique.category] = (counts[technique.category] || 0) + 1;
    return counts;
  }, {});
}
